application: nowplayingonsteam
version: 1
runtime: python
api_version: 1


handlers:

- url: /favicon\.ico
  static_files: assets/images/favicon.png
  upload: assets/images/favicon\.png

- url: /assets
  static_dir: assets

- url: .*
  script: main.py
  login: required
